"""empty message

Revision ID: 8b71c431ef53
Revises: 
Create Date: 2022-11-28 19:33:07.082611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b71c431ef53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('framework', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('ocurrences', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('unique_ocurrences', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('item')
    # ### end Alembic commands ###
